# Generated by Django 5.1.1 on 2024-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('price', models.PositiveBigIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('sales', models.PositiveBigIntegerField()),
            ],
        ),
    ]
